-- AlterTable
ALTER TABLE `Schedule` ADD COLUMN `capacity` INTEGER NOT NULL DEFAULT 30;

-- AlterTable
ALTER TABLE `Studio` MODIFY `platform` ENUM('WECHAT', 'NAVER', 'INSTAGRAM', 'YOUTUBE', 'OTHER') NOT NULL DEFAULT 'WECHAT';
